### ISSUE TITLE
如果我已经从cache中取到了数据了，为何还要通过url去拉取一次？

### ISSUE THREAD

**Issue by wander112900** [openboy2012/DDModel#1]
写的非常不错，只是有一个地方没看明白，dbSuccess，如果我已经从cache中取到了数据了，为何还要通过url去拉取一次？或者有什么地方控制的？

**Comment by openboy2012** [comment]
很高兴能收到你的提问，根据我们公司现在的业务，再获取URL的数据是保证数据的实时性

**Comment by wander112900** [comment]
那是不是可以把cache这部分独立出来，根据业务来取？
或者加一个开关，由业务来决定如果cache中有就从cache中取？
现在放在这里的作用应该只是在加载数据的时候先从cache中取出来防止出现空白页？

**Comment by openboy2012** [comment]
目前来说这个功能只是完成了这个目标，如果真的要把缓存功能做好的话需要服务端的配合，处理一些不经常改变的数据的时候就不需要从服务端获取了。

**Comment by openboy2012** [comment]
目前来说只是完成了你说的这个需求，如果真的想把缓存层做好的话需要服务端的配合，把一些不常改变的数据缓存在本机，写好更新策略。

**Comment by wander112900** [comment]
3226290100我的ＱＱ，可以加一下，以后多交流。

**Comment by jimckylin** [comment]
使用pod下来的编译报错，提示没有64位架构支持，xcode 版本6.3.1
