### ISSUE TITLE
如果一个实体的某个字段又是一个实体数组，有提供这个解析策略吗？

### ISSUE THREAD

**Issue by jimckylin** [openboy2012/DDModel#2]

**Comment by openboy2012** [comment]
有的，直接在 ‘parseMapping’ 方法里加入
 ‘id handlerOtherArray = [xxx mappingWithKey:@"xxx" mapping:[XXX parseMappings]]；
 return @{@"xxx":handlerOtherArray}; ‘就可以了

**Comment by jimckylin** [comment]
感谢回答！
